### ISSUE TITLE
Cointracking SEK conversion rate

### ISSUE THREAD

**Issue by PhotolyzeAnt** [bitsofwinter/cryptotaxsweden#10]
I noticed that the conversion rates used to calculate the "value in SEK"-column are often off by a lot on cointracking. I think this is because cointracking uses [bitcoinaverage](https://bitcoinaverage.com/) which seem to base their BTCSEK exchange rate on a just a few localbitcoin trades, see [this](https://bitcoinaverage.com/en/currency-markets/btc-to-sek), resulting in a very inaccurate value on some days.

A solution might be to set the cointracking currency to USD and then do conversions to SEK using the conversion rate from google finance. It is possible that this solution might break something else though.

**Comment by bitsofwinter** [comment]
Hmmm... interesting. I assumed they used the USD rates and then converted USD to SEK as you suggested. I did my own tax computation in an earlier version without using cointracking and got similar tax results between the two versions, that's why I didn't bother investigating their exchange rates in depth.

I'll see if I can setup a quick test using USD and see if the results are different.

**Comment by bitsofwinter** [comment]
I did a quick hack to test this and even though there is a difference, it is very small, at least for my own tax report.

The quick hack is pushed to the usdtest branch if you want to try it out. It requires the pandas package to be installed as well because I was to lazy to rewrite my old usd/sek conversion code.

**Comment by PhotolyzeAnt** [comment]
Thanks for the quick response! I'll give it a go with my numbers asap

**Comment by bitsofwinter** [comment]
Please let me know if this causes a big difference in tax for you. Would be good to know for other people who do their tax reports.

**Comment by PhotolyzeAnt** [comment]
I can't get it to run. I might be doing something stupid, but I tried:
`python report.py --format=sru 2017`

Which gave me this error:
`Exception: Didn't find an entry for date 2013-10-01 12:00:00`

I assumed this was because the rates only covered 2017 so I made my own usdsek.csv file that covered the whole range of dates, but then I ran into:
`Traceback (most recent call last):
  File "report.py", line 43, in <module>
    coin_report_filename=os.path.join(opts.out, "coin_report.csv") if opts.coin_report else None
  File "/cryptotaxsweden/tax.py", line 61, in compute_tax
    trade.sell_value *= to_sek(trade.date, "USD")
TypeError: can't multiply sequence by non-int of type 'float''`

**Comment by bitsofwinter** [comment]
I'm guessing your usdsek.csv file contains some close prices which pandas can't parse as decimal numbers so it reverts back to treating it as strings. Check the file contents and make sure all the values are decimal numbers.

**Comment by bitsofwinter** [comment]
I pushed an updated branch with usd sek prices for 2010-now.

**Comment by PhotolyzeAnt** [comment]
Thank you, the new branch did the trick! There was a 5% decrease in the final tax for me compared to the SEK version. I guess it would be helpful to have more people run the comparison to get more of a sample.

**Comment by bitsofwinter** [comment]
Interesting. For me there was a very minor increase in tax. ;) Yes more data would be needed. But it seems like it might be useful enough to integrate this functionality in the tool.

**Comment by bitsofwinter** [comment]
Which source did you choose for USD prices on cointracking btw?

**Comment by PhotolyzeAnt** [comment]
I used bitcoinaverage for the data reported above. However, changing the USD source doesn't seem to change any of the values in the "Value in USD" column on cointracking for me, even after recalculating trades, i.e. I end up with the same final tax regardless of USD source.
