### ISSUE TITLE
Adding "spend" to calculations

### ISSUE THREAD

**Issue by minbro22** [bitsofwinter/cryptotaxsweden#11]
Some of my transactions contains purchases with cryptoassets. I have marked them all as "spend" on cointracking and guess these need to be added in the script for the calculation to be correct? 

How are they handled now and if not handled at all could you please consider adding it to the script?

**Comment by bitsofwinter** [comment]
Spends are just ignored right now. If you know how they should be handled tax wise and it isn't too complicated I can add them to the script. As far as I remember, didn't you have to take the value of the thing you bought into account when computing the tax for a spend, or am I just remembering it wrong?

**Comment by bitsofwinter** [comment]
I read on skatteverket.se again and it actually seems like it should just be treated like a normal sell when spending so it is really simple to add support for it.

**Comment by bitsofwinter** [comment]
Support for spends have been added in the latest version. The releases haven't been updated yet though.

**Comment by minbro22** [comment]
You saving my day. Thank you!
Could you please also compile the new version for Windows so i can execute the script again? :smiley:

**Comment by bitsofwinter** [comment]
I've added new releases for win/mac now.
