### ISSUE TITLE
Why are prices in SEK rounded?

### ISSUE THREAD

**Issue by mburazin** [bitsofwinter/cryptotaxsweden#12]
Hi,

I have a question on why are all the SEK amounts (försäljningspris, omkostnadsbelopp, vinst, förlust) in the K4 form rounded to whole numbers? Isn't the script calculating always using floating point numbers ? Why not show it with decimals in K4 ?

Thanks,
Marko.

**Comment by bitsofwinter** [comment]
When reporting online on skatteverket.se there is no support for decimal numbers.
