### ISSUE TITLE
Importing the files to skatteverket

### ISSUE THREAD

**Issue by blasut** [bitsofwinter/cryptotaxsweden#13]
Hi, thanks for the script!

I'm trying to upload the generated .sru file(s) to my Deklaration, but I'm not sure where I'm supposed to do it. When I add a K4-bilaga, and try the "importera" button I get an error saying: " Filen info/blanketter.sru innehåller inga K4-försäljningar. ".

What am I doing wrong?

**Comment by bitsofwinter** [comment]
I think you might be doing it correctly, it should be an import button which you use. Have you checked if the report actually contains any trades?

**Comment by blasut** [comment]
They worked when I tried uploading to the test site, the "Filöverföring" page. But not directly to the "Bilaga".

**Comment by bitsofwinter** [comment]
Ok, weird. Is it solved for you then? I.e. you could use the results after uploading to "Filöverföring" to send in the tax report?

**Comment by blasut** [comment]
Well, sort of. I uploaded the files via ”Filöverföringen”, but I cant edit the fields I need on my Deklaration. 

Hmhm, I’m gonna call them tomorrow I guess.

**Comment by bitsofwinter** [comment]
Ok, if you get any feedback that can be useful for improving the sru-generation, let me know.

**Comment by blasut** [comment]
Will do! Like you say, it’s a bit strange, but might be a limitation of the number of trades or something. Will let you know, what Skatteverket says.

**Comment by bitsofwinter** [comment]
Aha, yes, there is a limit to the number of trades when using the "importera" button. 200 or 300 trades or similar.

You can do a simplified report now though, Skatteverket allows an aggregated type of reporting where profits/losses are aggregated so it only becomes 1-2 entries reported per coin.

The script can generate a simplified report using the "--simplified-k4" argument.

**Comment by blasut** [comment]
I tried that as well, but i still doesn’t work :/. Weird isn’t it? I get the same errors

**Comment by blasut** [comment]
So the solution was that I wrote down section 7.5 and 8.4 in "Övriga upplysningar". This was how Skatteverket told me to do it anyway.

**Comment by umbrellasalesman02** [comment]
For future readers:

For me it worked to import the generated `info.sru` and `blanketter.sru` from

1.  https://www.skatteverket.se/filoverforing.  ->
2.  Filöverförning - Inloggning  ->
3.  Inkomstdeklaration -> 
4.  Överföra filer

I'm very thankful for this service by the way.  Great job! I'm a programmer / code monkey myself but math isn't my strong suit..  Would you be ok with a Swish donation instead of crypto? @bitsofwinter

**Comment by bitsofwinter** [comment]
@jonahe Nice that it worked out for you with the upload and thanks for documenting it for others. Thanks for considering doing a donation. Regarding Swish donations, I would prefer not to give out my phone number because I want to stay semi anonymous. I think crypto donations will be the only option for the time being at least.

**Comment by umbrellasalesman02** [comment]
@bitsofwinter I understand. I just sent you some ETH. Thanks again for creating and maintaining this project! Awesome job!

**Comment by bitsofwinter** [comment]
@jonahe Thanks for the donation and the kind words!

**Comment by Ninj201** [comment]
Hello! I just recently sent in the simplified K4 .sru file. But I am confused where I find Övriga Upplysningar to paste the rounding_report in at.

**Comment by bitsofwinter** [comment]
Hi! It is not super easy to find. I don't remember exactly where but there was an option to modify existing prefilled data or similar and in there you could find the "Övriga upplysningar" field. Search around and I think you will find it.

**Comment by Ninj201** [comment]
Thanks for the reply!
Yeh I looked around and found it here:
https://skatteverket.se/ -> Inkomstdeklaration 1 -> Ändra -> 17.Övriga upplysningar
