### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by jimmywinberg** [bitsofwinter/cryptotaxsweden#17]
Getting this error.

Traceback (most recent call last):
  File "report.py", line 38, in <module>
  File "taxdata.py", line 98, in read_from
IndexError: list index out of range
[15240] Failed to execute script report

File: exported trades.csv from cointracking
Edited the personal template.

**Comment by bitsofwinter** [comment]
Did you download the csv from the Trade Prices page?

**Comment by jimmywinberg** [comment]
Yes i have, i created 2 test trades and export it and then run the script.
Is it possible i do something wrong when inputing the trades?
________________________________
Från: bitsofwinter <notifications@github.com>
Skickat: den 29 juli 2018 10:26
Till: bitsofwinter/cryptotaxsweden
Kopia: BarbieAction; Author
Ämne: Re: [bitsofwinter/cryptotaxsweden] Unable to run (#17)


Did you download the csv from the Trade Prices page?

**Comment by bitsofwinter** [comment]
Can you send the first line from the csv-file? It only contains headers so it doesn't let anyone know about your trades.

**Comment by jimmywinberg** [comment]
Just made a sample trade and mining.

"Type","Buy","Cur.","Sell","Cur.","Fee","Cur.","Exchange","Group","Comment","Date"
"Mining","1.00000000","ZEC","","","","","","","","2018-07-30 15:25:12"
"Trade","1.00000000","ZEC","1.00000000","2000","","","","","","2018-07-30 15:25:12"
________________________________
Från: bitsofwinter <notifications@github.com>
Skickat: den 30 juli 2018 08:16
Till: bitsofwinter/cryptotaxsweden
Kopia: BarbieAction; Author
Ämne: Re: [bitsofwinter/cryptotaxsweden] Unable to run (#17)


Can you send the first line from the csv-file? It only contains headers so it doesn't let anyone know about your trades.

**Comment by bitsofwinter** [comment]
What is the setting for "Your currency" on this page?

https://cointracking.info/settings.php

**Comment by jimmywinberg** [comment]
Set to Swedish crown

Med vänliga hälsningar
Jimmy Winberg
________________________________

**Comment by bitsofwinter** [comment]
There should be columns called "Value in SEK" and "Value in BTC" on this page, are they there or missing?

https://cointracking.info/trade_prices.php

**Comment by jimmywinberg** [comment]
Please see image

[Image]
Med vänliga hälsningar
Jimmy Winberg
________________________________

**Comment by bitsofwinter** [comment]
Seems like there was a problem with the attached image.

**Comment by jimmywinberg** [comment]
https://ibb.co/dDGTto

I can see btc value and value in sek

Med vänliga hälsningar
Jimmy Winberg
________________________________

**Comment by bitsofwinter** [comment]
Just to be 100% sure, can you press the csv-button on that page and download the csv again and double check that those fields ("Value in SEK" and "Value in BTC") are not available in the csv?

**Comment by jimmywinberg** [comment]
﻿"","Type","Buy","Cur.","Value in BTC","Value in SEK","Sell","Cur.","Value in BTC","Value in SEK","Spread","Exchange","Group","Date"
"","Mining","1.00000000","ZEC","0.02598153","1853.11","-","","-","-","-","","","30.07.2018 15:25"
"","Trade","1.00000000","ZEC","0.02598153","1853.11","1.00000000","2000","0.00000000","0.00","-100.00 %","","","30.07.2018 15:25"

Now they are available, seem i exported csv file from wrong dahsboard/link.
I will test new csv file tomorow as im not able to now. But it looks more correct in csv file exported from trade_prices
________________________________
Från: bitsofwinter <notifications@github.com>
Skickat: den 30 juli 2018 18:32
Till: bitsofwinter/cryptotaxsweden
Kopia: BarbieAction; Author
Ämne: Re: [bitsofwinter/cryptotaxsweden] Unable to run (#17)


Just to be 100% sure, can you press the csv-button on that page and download the csv again and double check that those fields ("Value in SEK" and "Value in BTC") are not available in the csv?
