### ISSUE TITLE
help needed! what did I do wrong here?

### ISSUE THREAD

**Issue by Instantexit** [bitsofwinter/cryptotaxsweden#19]
I get this error report, I probably entered something wrong in cointracking. Any ideas how I can correct this?

"Exception encountered at line 111 in trades csv-file: Not enough coins available for BTC, 0.0332219 < 0.03322191.
Aborting tax computation."

**Comment by bitsofwinter** [comment]
I can't say exactly why you have this case of selling slightly more coins than you bought but it might just be that the exchange where you bought it rounds the value more than the exchange where you sold it.

In any case. I added a new option now --max-overdraft which you can try out. In this case your overdraft for this coin is only 0.00000001. If you add the following option I think it will work and this minor overdraft will be ignored.

--max-overdraft 0.00000001

Note: I haven't updated the windows/mac binaries yet so you'll have to use set it up from source until the new binaries are created.

**Comment by Instantexit** [comment]
Thanks! 
This is the line it is not happy with.
,"Trade","1.23345070","XMR","0.03351545","3159.82","0.03322191","BTC","0.03322191","3132.14","-0.88   %","Cryptopia","cryptopia","20.02.2018   17:35"

 Could it be that I have forgotten to input a trade somewhere, as one exchange .csv export didnt work and I had to manually input the trades on that exchange? Or is there something wrong with this particular line? 

I dont know how to make the py script into an executable, is that done with pyinstaller or?

Thanks for this tool btw, very neat.


--

**Comment by Instantexit** [comment]
I am too computer illiterate to get the .bat included to make me a report.exe so i tried installing python and needed additions to it. I get this: python report.py 2018 --simplified-k4 --max-overdraft 0.00000001
  File "report.py", line 50
    print(f"Aborting tax computation.")
                                     ^
SyntaxError: invalid syntax

If you have time to help me or update the released exe id be very happy. Im still a newb with this stuff ;)

**Comment by bitsofwinter** [comment]
Added a new release now which includes the latest changes.
