### ISSUE TITLE
Conversion rates for 2018

### ISSUE THREAD

**Issue by ABEC7** [bitsofwinter/cryptotaxsweden#21]
Any chance you could add conversion rates (USD/SEK) for all of 2018? The current file only covers Q1 2018.

Other than that I guess the current version should work just fine for 2018 as well (after adding the K4 template for 2018 to the data folder), right?

How are fees handled btw? Are they included in the purchase price?

**Comment by bitsofwinter** [comment]
Added now.

**Comment by ABEC7** [comment]
Thanks!
