### ISSUE TITLE
Exception encountered at line 442

### ISSUE THREAD

**Issue by JoakimFalk** [bitsofwinter/cryptotaxsweden#26]
Hello there, I am a tad puzzled, 
Command :  report 2018 --simplified-k4
Exception encountered at line 442 in trades csv-file: Selling currency ETH which has not been bought yet Aborting tax computation.

It is the data from Binance > Cointracking > CSV, Any idea what am I missing here?.

Thank you.

**Comment by FilipeRA** [comment]
I've had the same issue and variations of it. Before you export the CSV from Trade Prices, sort the trades from oldest to newest. I believe the script has some issue when sorting the export file.

**Comment by Instantexit** [comment]
if you use the latest Python version and not executable, this issue of
sorting is fixed (at least for me)


Den tors 18 apr. 2019 15:59FilipeRA <notifications@github.com> skrev:

**Comment by JoakimFalk** [comment]
I am using the exe, but perhaps should get Ubuntu and run py for next year. This year I think it all is sorted from another service. Thank you for replies.

**Comment by bitsofwinter** [comment]
Sorry for the late reply. I'm back from vacation now so I'll put on the todo list to update the exe file.

Which service did you use for tax reporting? Always interested in the alternatives available. :-)

**Comment by bitsofwinter** [comment]
New release added with binary for Windows. Mac packaging script does not work anymore for some reason and I don't have time to fix it right now.

**Comment by JoakimFalk** [comment]
Thank you, I found a service called Monetax
