### ISSUE TITLE
Not enough coins available for {self.symbol}, {self.amount} < {amount}

### ISSUE THREAD

**Issue by metalmetalmetal** [bitsofwinter/cryptotaxsweden#6]
Executing this using python3, exposing trades.csv in the data directory, I get this:

```python
pi@raspberrypi:~/cryptotaxsweden $ python3 report.py 2017
Traceback (most recent call last):
  File "report.py", line 7, in <module>
    import tax
  File "/home/pi/cryptotaxsweden/tax.py", line 25
    raise Exception(f"Not enough coins available for {self.symbol}, {self.amount} < {amount}.")

SyntaxError: invalid syntax
```

It's a bit hard to determine what's going wrong here;

* Is there something wrong in my trades.csv file?

I would assume that the script wanted to echo the symbol and amounts with their actual values, but I seem to only get it in their code authored form.

**Comment by metalmetalmetal** [comment]
I am actually suspecting some incompatibilities with Raspberry Pi Stretch and the requirements set by the script.
Python 3.6 seem to be an unsupported version for the raspberry pi, as the one that is exposed through apt is 3.5.3, which I guess won't work.

**Comment by bitsofwinter** [comment]
String interpolation, i.e. the f"" format, was added in Python 3.6. If you have 3.5 it won't work.

If you want to convert it to Python 3.5 you can change the string formatting, but I'm guessing installing a newer version of Python will be easier.

**Comment by metalmetalmetal** [comment]
Indeed correct. The python version was the culprit. I now at least got past that hurdle, and am now going to have to sort out the abundance of `Exception: Selling currency BCN which has not been bought yet` that are littered all over the place.
