### ISSUE TITLE
Not enough coins avaliable for BTC

### ISSUE THREAD

**Issue by minbro22** [bitsofwinter/cryptotaxsweden#7]
I keep getting the error "Not enough coins avaliable for BTC  0.00XXX < 0.00XXXX" when trying to run the script. All transactions are imported and deposit/withdraw from Exchange as well. 

The most generated income is mining deposits beside a few cash deposits. Can the script identify mining income?

**Comment by bitsofwinter** [comment]
Mining income should be reported as Mining on cointracking and then the script will be able to handle it. You will have to manually report taxes for mining as "Inkomst från hobbyverksamhet" though if you have made a profit, this is done on a different form than the K4.
