### ISSUE TITLE
Expanding the README/Cointracking use docs

### ISSUE THREAD

**Issue by metalmetalmetal** [bitsofwinter/cryptotaxsweden#8]
I could make a pull request to expand on the documentation about this, as I believe it's one of the things that pop up frequently.

I believe the message `raise Exception(f"Selling currency {trade.sell_coin} which has not been bought yet")` usually occur because deposits and withdraws aren't recorded properly?

But, since I'm not overly familiar with all the situations that could raise this issue, I'd like to ask if there are other variants to this?

I think that could be put into the FAQ area of the README, or maybe better yet, inside the Wiki.

**Comment by bitsofwinter** [comment]
Deposits and withdrawals don't matter for the tax report as the script handles it. I've only used deposit/withdrawal to record transfers between my own wallets and this doesn't matter for the tax report.

I'll write some more about this in the README to try to clarify it.

**Comment by metalmetalmetal** [comment]
The README update helped, thanks for that.

So, in practice, deposits and withdraws are ignored by the script?
I think I'm running into issues where I'm trying to sell a coin that hasn't been bought by bitcoins, but instead been acquired through mining, in which the code spits out that I can't "sell something I haven't bought yet".

**Comment by bitsofwinter** [comment]
Mining should just be reported as a trade type of "Mining" on cointracking, then it will be picked up by the script.
